/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://zeo2ii4z5fa5bcgajwhsxeam2m.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4hbvln2msjb33mr54t2zwooore",
    "aws_cognito_identity_pool_id": "us-east-2:fa654365-0f58-451f-8d70-2cd259aaef6d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wQk66Cagb",
    "aws_user_pools_web_client_id": "6jgats5n47lrn4lmaordta6hb6",
    "oauth": {
        "domain": "d7on4c0ot1d0-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/premium",
        "redirectSignOut": "http://localhost:3000/premium",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "6b4a2381dcf6442b86d0e73f1dc1de6d",
    "aws_mobile_analytics_app_region": "us-east-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "6b4a2381dcf6442b86d0e73f1dc1de6d",
            "region": "us-east-2"
        }
    }
};


export default awsmobile;
